plugins:
  discourse_size_enabled:
    default: true
    client: true
  discourse_size_default_max_growth_rate:
    default: 1000
    client: true
    type: float
  discourse_size_min_base_size:
    default: 100
    client: true
    type: float
  discourse_size_max_base_size:
    default: 300.0
    client: true
    type: float
  discourse_size_points_per_invite:
    default: 50
    type: integer
  discourse_size_points_per_invited:
    default: 100
    type: integer
  discourse_size_points_per_reply:
    default: 5
    type: integer
  discourse_size_points_per_topic:
    default: 15
    type: integer
  discourse_size_points_per_daily_login:
    default: 20
    type: integer
  discourse_size_points_per_read:
    default: 1
    type: integer
  discourse_size_help_url:
    default: ""
    client: true
  discourse_size_percentage_per_point:
    default: 0.1
    client: true
    type: float
  discourse_size_point_damping:
    default: 0.8
    client: true
    type: float
