plugins:
  discourse_size_enabled:
    default: true
    client: true
  discourse_size_disable_properties:
    default: false
    client: true
  discourse_size_disable_triggers:
    default: false
    client: true
  discourse_size_min_base_size:
    default: 100
    client: true
    type: float
  discourse_size_max_base_size:
    default: 300
    client: true
    type: float
  discourse_size_daily_reward_amount:
    default: 10
    type: integer
    client: true
  discourse_size_daily_quests_count:
    default: 3
    type: integer
  discourse_size_extra_reward_amount:
    default: 50
    type: integer
  discourse_size_conversation_category_ids:
    default: ""
  discourse_size_content_category_ids:
    default: ""
  discourse_size_chat_channel_id:
    default: 0
    type: integer
  discourse_size_leaderboard_trend_hours:
    default: 24
    type: integer
  discourse_size_help_url:
    default: ""
    client: true
  discourse_size_trigger_category_slug:
    default: ""
    client: true
  discourse_size_shop_name:
    default: "Size Shop"
    client: true
  discourse_size_shop_items:
    default: "[]"
    client: true
    type: textarea
